repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.89.1
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color
    - id: terraform_tflint
      args:
        - --args=--recursive
    - id: terraform_tfsec
      args:
        - >
          --args=--format json
          --no-color
    - id: terraform_docs
      args:
        - --args=--config=.terraform-docs.yml